[package]
name = "ruff-wasm"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = "s"

[dependencies]
ruff_wasm = { git = "https://github.com/charliermarsh/ruff.git", version = "0.0.0" }
wasm-bindgen = "0.2.86"